site_name: A Stripe Checkout Integration Quickstart for Beginners
site_url: https://codymauro.github.io/stripe-payment-guide/

theme:
  name: material
  features:
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - navigation.sections

nav:
  - Overview: index.md
  - Prerequisites: prerequisites.md
  - Frontend and Backend Setup: code.md
  - Make a $10 Payment: integration.md
  - System Responses: response.md
  - Troubleshooting: troubleshoot.md

markdown_extensions:
  - admonition
  - toc:
      permalink: true

extra_css:
  - styles/extra.css
